nodeLinker: node-modules
enableGlobalCache: false
yarnPath: .yarn/releases/yarn-1.22.22.cjs

# Equivalent to save-exact=true - save exact versions
savePrefix: ""

# Equivalent to engine-strict=true - enforce engines field
enableStrictSsl: true
enableHardenedMode: true

# Equivalent to disabling audit and fund messages
enableTelemetry: false
enableMessageNames: false
logFilters:
  - code: YN0013
    level: discard
